name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Delete old liquibase core package
        uses: actions/delete-package-versions@v3
        with:
          owner: 'phyworks'
          repo: 'liquibase'
          package-name: 'phyworks.liquibase.liquibase-core'
          min-versions-to-keep: 3
      - name: Delete old liquibase package
        uses: actions/delete-package-versions@v3
        with:
          owner: 'phyworks'
          repo: 'liquibase'
          package-name: 'phyworks.liquibase.liquibase'
          min-versions-to-keep: 3

      - name: Build
        run: |
          mvn versions:set -DnewVersion=4.6.2-b${{ github.run_number }}
          mvn clean deploy -DskipTests=true
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
